Add enketo-preview url routed to PreviewXFormListViewSet
onaio/onadata pull request #1953
Opened 2020-11-23 14:30 UTC by FrankApiyo

### Changes / Features implemented
Add a new URL that is routed to `PreviewXFormListViewSet`
### Steps taken to verify this change does what is intended
[TO ADD]

Closes #1952

2020-11-25 07:40 UTC, ukanga reviewed
Just concerned we do not have test to perhaps check this will work as expected Perhaps in `onadata/apps/api/tests/viewsets/test_xform_list_viewset.py` as was the case when we introduced the [/enketo path](https://github.com/onaio/onadata/commit/e82747827f522bb60f191d09617e9f9fa18de1d6#diff-b8a6e4ab17d4bfdc0b7715074bfbe0b8919d38166d7e6e45cf91dad979d1a27d).

2020-11-25 12:22 UTC, ukanga approved these changes

2020-11-25 12:25 UTC, ukanga reviewed
Could we also add some documentation in the docs for this new endpoint as well perhaps on the enketo endpoint. Check with @DavisRayM on the full docs for both endpoints.

2020-12-03 07:56 UTC, ivermac requested changes
Is it correct to assume that `PreviewXFormListViewSet` has already been implemented?

2020-12-03 07:56 UTC, ivermac commented on docs/formlist.rst
> +    curl -X GET https://stage-api.ona.io/<user_name>/<form_pk>/formList
Can we use `api.ona.io` on our example urls?

2020-12-03 07:56 UTC, ivermac commented on docs/formlist.rst
> +    curl -X GET https://stage-api.ona.io/enketo/<form_pk>/formList
Same comment as above

2020-12-03 07:56 UTC, ivermac commented on docs/formlist.rst
> +    curl -X GET https://stage-api.ona.io/enketo-preview/<form_pk>/formList
Same comment as above?

2020-12-03 08:01 UTC, FrankApiyo commented
> Is it correct to assume that `PreviewXFormListViewSet` has already been implemented?

@ivermac yes! https://github.com/onaio/onadata/blob/master/onadata/apps/api/viewsets/xform_list_viewset.py#L167

2020-12-03 08:15 UTC, ivermac approved these changes

2020-12-03 10:01 UTC, ukanga approved these changes
Can you ensure that all checks are passing?

2020-12-03 11:29 UTC, merged