Add pagination headers to the paginated DataViewSet response
onaio/onadata pull request #1977
Opened 2021-01-07 08:02 UTC by DavisRayM

### Changes / Features implemented

- Add `next_page` & `previous_page` headers to the paginated response from the DataViewSet
- Update test

### Steps taken to verify this change does what is intended

- Updated tests

### Side effects of implementing this change

- N/A

Closes #1969

2021-01-07 08:27 UTC, ivermac submitted a review, later dismissed

2021-01-07 12:44 UTC, ukanga requested changes
Let's use the Link header as described https://tools.ietf.org/html/rfc5988. See Github's implementation for inspiration as well https://docs.github.com/en/free-pro-team@latest/rest/guides/traversing-with-pagination.

2021-01-08 15:10 UTC, ukanga commented on docs/data.rst
> +
We could add a reference to the RFC on the link header text. See the GitHub docs references on this for inspiration.

2021-01-11 13:29 UTC, ukanga approved these changes

2021-01-11 21:08 UTC, merged