Update application dependencies
onaio/onadata pull request #2309
Opened 2022-08-23 07:05 UTC by DavisRayM

### Changes / Features implemented

- Update python dependency versions

### Steps taken to verify this change does what is intended

N/A

### Side effects of implementing this change

N/A

2022-08-23 09:46 UTC, KipSigei approved these changes

2022-08-31 10:29 UTC, ukanga requested changes

2022-08-31 10:29 UTC, ukanga commented on .pylintrc
> +disable=print-statement,parameter-unpacking,unpacking-in-except,old-raise-syntax,backtick,long-suffix,old-ne-operator,old-octal-literal,import-star-module-level,raw-checker-failed,bad-inline-option,l
On, `imported-auth-user., could we make the necessary changes on the imports instead of disabling this check, please?

2022-08-31 16:36 UTC, ukanga approved these changes

2022-09-01 12:11 UTC, ukanga approved these changes

2022-09-01 12:18 UTC, merged