Data endpoint enhancements
onaio/onadata pull request #2477
Opened 2023-09-15 14:15 UTC by kelvin-muchiri

### Changes / Features implemented

### Steps taken to verify this change does what is intended

### Side effects of implementing this change

**Before submitting this PR for review, please make sure you have:**

  - [ ] Included tests
  - [ ] Updated documentation

Closes #2472

2023-09-27 07:58 UTC, KipSigei requested changes

2023-09-27 07:58 UTC, KipSigei commented on onadata/apps/api/tasks.py
> +    try:
Can we wrap this block in a condition such that if `xform.is_instance_json_regenerated` is True then we dont need to execute it

2023-09-27 08:02 UTC, ukanga requested changes

2023-09-27 08:02 UTC, ukanga commented on docs/forms.rst
> +            "status": "STARTED"
This should be a management command and not an API.

2023-09-28 13:11 UTC, KipSigei approved these changes

2023-09-28 13:58 UTC, merged